Repository sonic-net/sonic-linux-kernel, pull requests merged in 2024-12, with the labels that each got.

#446 Integrate HW-MGMT 7.0040.2000 Changes
  patch/0048-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
  patch/0095-platform-mellanox-nvsw-sn2201-Add-support-for-new-sy.patch
  patch/kconfig-inclusions
  patch/series
Labels: Request for 202405 Branch, Cherry Pick Conflict_202405

#448 [PCI/ASPM] Revert commit `456d8aa` to avoid kernel panics in `6.1.94`
  patch/revert-456d8aa-to-fix-pcie_aspm_exit_link_status.patch
  patch/series
Labels: P0

#449 Fix default kernel version
  Makefile
Labels: Request for 202405 Branch, Request for 202411 Branch
