Repository sonic-net/sonic-linux-kernel, pull requests merged in 2025-07, with the labels that each got.

#491 [build] Use package.trafficmanager instead of sonicstorage.blob
  Makefile
Labels: Request for 202305 Branch

#493 [action] [PR:490] [build] Use package.trafficmanager instead of sonicstorage.blob
  Makefile
Labels: automerge

#489 Integrate HW-MGMT Version 7.0040.4019
  patch/kconfig-inclusions
Labels: Request for 202505 Branch

#500 Ignore table if the EFI memory attributes are corrupt
  patch/0001-efi-memattr-Ignore-table-if-the-size-is-clearly-bogus.patch
  patch/series
Labels: Request for msft-202412 Branch, Request for 202505 Branch
