Repository sonic-net/sonic-linux-kernel, pull requests merged in 2025-01, with the labels that each got.

#407 Fix optoe's write_max when using native i2c driver
  patch/driver-support-optoe-write-max_fix.patch
  patch/series
Labels: Request for 202411 Branch

#455 [action] [PR:449] Fix default kernel version
  Makefile
Labels: automerge

#456 [action] [PR:407] Fix optoe's write_max when using native i2c driver
  patch/driver-support-optoe-write-max_fix.patch
  patch/series
Labels: automerge

#458 [Mellanox] Integrate HW-MGMT Version 7.0040.2104 Changes
  patch/0048-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
  patch/0092-platform-mellanox-Introduce-support-of-Nvidia-smart-.patch
  patch/0097-platform-mellanox-mlx-platform-Add-support-for-new-N.patch
  patch/kconfig-inclusions
  patch/series
Labels: Platform: Mellanox, Request for 202411 Branch

#451 [202405][Mellanox]Integrate HW-MGMT Version 7.0040.2101 Changes
  patch/0048-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
  patch/0092-platform-mellanox-Introduce-support-of-Nvidia-smart-.patch
  patch/0097-platform-mellanox-mlx-platform-Add-support-for-new-N.patch
  patch/kconfig-inclusions
  patch/series
Labels: Platform: Mellanox
